import Layout from '@/Layout/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/profile-removebg.png"
import AnimateHeading from '@/components/Animate/AnimateHeading'
import Link from 'next/link'
import LinkArrow from '@/components/IconComponents/LinkArrow'
import HireMe from '@/components/HireMe'

export default function Home() {
  return (
    <>
      <Head>
        <title>Vivek Singh</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className=' flex items-center text-dark min-h-screen '>
        <Layout className="pt-0">
          <div className=' flex items-center justify-between w-full'>

            {/* Heading */}
            <div className=' w-1/2 flex flex-col items-center self-center '>
              {/* Heading intro */}
              <AnimateHeading text={`I'm software engineer gradute with passion of problem-sloving.`} className=" !text-5xl !text-left "/>
              <p className=' my-4 text-base font-medium '> As a skilled full-stack developer, I am dedicated to turning ideas into innovative applications. 
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>

              {/* Two Button for more */}
              <div className=' flex items-center self-start mt-2 space-x-5 '>
                {/* For resume pdf */}
                <Link href="/" target={"_blank"}
                  className=' flex items-center self-center text-center text-lg ring-2 ring-transparent ring-offset-0 hover:ring-dark p-2 px-4 rounded-lg font-semibold bg-dark text-light hover:bg-dark/5 active:bg-green-100 hover:text-dark transition-all hover:shadow-inner hover:scale-105 duration-500 ease-out' 
                >Resume <LinkArrow className={" w-6 ml-1 "}/></Link>
                {/* send email to my address */}
                <Link href="mailto:singhvivekkumar309@gmail.com" target={"_blank"}
                  className=' flex items-center self-center text-center text-lg ring-2 ring-dark ring-offset-0 p-2 px-4 rounded-lg font-semibold hover:bg-dark/5 active:bg-dark/5  transition-all hover:shadow-inner hover:scale-105 duration-500 ease-out underline underline-offset-1 '
                >CONTACT</Link>
              </div>
            </div>

            {/* profile photo */}
            <div className=' w-1/2'>
              <Image alt='Vivek Singh' className='w-full h-auto' src={profilePic}/>
            </div>
          </div>
        </Layout>
        <HireMe/>
      </main>
    </>
  )
}
