import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Vivek Singh</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
      </main>
    </>
  )
}
